Map<String, Map<String, String>> teksBahasa = {
  'id': {
    'qibla_app': 'Qibla+ App',
    'metode_perhitungan': 'Metode Perhitungan',
    'mode_gelap': 'Mode Gelap',
    'bahasa': 'Bahasa',
    'suara_adzan': 'Suara Adzan',
    'hubungi_developer': 'Hubungi Developer di:',
    'subuh': 'SUBUH',
    'dzuhur': 'DZUHUR',
    'ashar': 'ASHAR',
    'maghrib': 'MAGHRIB',
    'isya': 'ISYA',
  },
  'en': {
    'qibla_app': 'Qibla+ App',
    'metode_perhitungan': 'Calculation Method',
    'mode_gelap': 'Dark Mode',
    'bahasa': 'Language',
    'suara_adzan': 'Adhan Sound',
    'hubungi_developer': 'Contact Developer:',
    'subuh': 'FAJR',
    'dzuhur': 'DHUHR',
    'ashar': 'ASR',
    'maghrib': 'MAGHRIB',
    'isya': 'ISHA',
  },
  'ar': {
    'qibla_app': 'تطبيق القبلة',
    'metode_perhitungan': 'طريقة الحساب',
    'mode_gelap': 'الوضع الداكن',
    'bahasa': 'اللغة',
    'suara_adzan': 'صوت الأذان',
    'hubungi_developer': 'تواصل مع المطور:',
    'subuh': 'الفجر',
    'dzuhur': 'الظهر',
    'ashar': 'العصر',
    'maghrib': 'المغرب',
    'isya': 'العشاء',
  },
};
